initializing `Trainer()` object
`Trainer()` has been initialized
Begin Training
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Traceback (most recent call last):
  File "siamese_train.py", line 96, in <module>
    trainer.fit(net, train_datamodule)
  File "/home/cougarnet.uh.edu/eeplater/anaconda3/envs/deep_sort/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/cougarnet.uh.edu/eeplater/anaconda3/envs/deep_sort/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cougarnet.uh.edu/eeplater/anaconda3/envs/deep_sort/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/cougarnet.uh.edu/eeplater/anaconda3/envs/deep_sort/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1138, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/cougarnet.uh.edu/eeplater/anaconda3/envs/deep_sort/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1438, in _call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/home/cougarnet.uh.edu/eeplater/anaconda3/envs/deep_sort/lib/python3.6/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/improved_Deep_SORT/siamese_net.py", line 193, in setup
    self.siamese_dataset = SiameseTriplet(imageFolderDataset=folder_dataset,
NameError: name 'SiameseTriplet' is not defined